---
- name: Set up docker
  hosts: server
  become: true
  vars:
    system_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - python3-setuptools
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ system_packages }}"
        state: latest
        update_cache: yes
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: yes
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull Jenkins Docker image
      docker_image:
        name: jenkins/jenkins
        source: pull
    - name: Create Jenkins container
      docker_container:
        name: jj
        image: jenkins/jenkins
        published_ports:
          - "8080:8080"
        state: started
