pipeline {
	agent any
	environment {
		PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	}
	options {
		ansiColor('xterm')
	}
	stages {
		stage ("Test") {
			steps {
				echo "test"
			}
		}
		stage ('Display versions') {
			steps {
				sh '''
				source $HOME/my_env/bin/activate
				docker -v
				python -V
				ansible --version
				molecule --version
				'''
			}
		}
		stage ('Molecule converge') {
			steps {
				dir("roles/simple_web") {
					sh '''
					source $HOME/my_env/bin/activate
					molecule converge
					'''
				}
			}
		}
		stage ('Molecule verify') {
			steps {
				dir("roles/simple_web") {
					sh '''
					source $HOME/my_env/bin/activate
					molecule verify
					'''
				}
			}
		}
	}
	post {
		always {
			dir("roles/simple_web") {
				sh '''
				source $HOME/my_env/bin/activate
				molecule destroy
				'''
			}
		}
	}
}
