pipeline {
	agent any
	environment {
		PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	}
	stages {
		stage ("Test") {
			steps {
				echo "test"
			}
		}
		stage ('Display versions') {
			steps {
				sh '''
				source $HOME/my_env/bin/activate
				docker -v
				python -V
				ansible --version
				molecule --version
				'''
			}
		}

		stage ('Molecule test') {
			steps {
				sh '''
				source $HOME/my_env/bin/activate
				molecule converge
				'''
			}
		}
	}
}
